research_task:
  description: >
    Make sure you find any interesting and relevant information about todo's given
    the current year is {current_month} {current_year}.
  expected_output: >
    A list with  bullet points of the most relevant information about todo's given
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst



